name: marita
description: Marita — AI-powered financial fraud detection for startups.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Routing
  go_router: ^17.2.3

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  google_sign_in: ^7.2.0

  # Icons
  iconsax_plus: ^1.0.0

  # Utilities
  intl: ^0.20.2
  flutter_svg: ^2.2.4
  flutter_markdown: ^0.7.7+1
  file_picker: ^11.0.2
  image_picker: ^1.2.2
  uuid: ^4.5.3
  firebase_storage: ^13.3.0
  path_provider: ^2.1.5
  csv: ^8.0.0
  pdf: ^3.12.0
  printing: ^5.14.3
  shared_preferences: ^2.5.5
  share_plus: ^12.0.2
  iconsax: ^0.0.8
  firebase_ai: ^3.11.0
  firebase_app_check: ^0.4.3
  excel: ^4.0.6
  xml: ^6.6.1
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#E4FF1A"
  image: "assets/logos/Splash icon.png"
  android_12:
    color: "#E4FF1A"
    image: "assets/logos/Splash icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/Logobug black bg.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/

  # fonts:
  #   - family: PlusJakartaSans
  #     fonts:
  #       - asset: assets/fonts/PlusJakartaSans-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/PlusJakartaSans-Bold.ttf
  #         weight: 700
