// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABaw-h8ebvWLeRXdmv7-Qum_ouuhPPGOA',
    appId: '1:948284825345:web:18faee11fbbd375e164500',
    messagingSenderId: '948284825345',
    projectId: 'marita-ai-fintech',
    authDomain: 'marita-ai-fintech.firebaseapp.com',
    storageBucket: 'marita-ai-fintech.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpPlpUilG-tuh4Tw8nGlQpaDbtPjy0nuo',
    appId: '1:948284825345:android:36b5626a0657fc15164500',
    messagingSenderId: '948284825345',
    projectId: 'marita-ai-fintech',
    storageBucket: 'marita-ai-fintech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4w5BA5rMOMMQefQWILbGUt9KQC5Lw3XM',
    appId: '1:948284825345:ios:d334e80bd0c6853d164500',
    messagingSenderId: '948284825345',
    projectId: 'marita-ai-fintech',
    storageBucket: 'marita-ai-fintech.firebasestorage.app',
    iosBundleId: 'com.marita.marita',
  );
}
